language: groovy
jdk:
- oraclejdk8
dist: xenial
sudo: false
branches:
  only:
  - master
  - develop
  - FFTF-UPGRADE-1.5.2
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/wrapper/"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish --stacktrace
  --info '
env:
  global:
  - secure: kxpAcJEe7UNGDXTD7nOUKcC2ERLn8AAV0nlymOyZIdQkKM9g2eHxt62zx3pwlHrcvqBH4TNvXQ6veO/Ij3l0o+i4qpvqRacla4B0Q4T8vgSIGZU9tD2bi7z7oxf19hIbIhDwG0vGyRt95dKn/52XRmHTlD3T3ZJ0WvkylJkXVdvLlW7ujN1+yiJU0rCpQx1zx6bEYjYOUFGDrqdKLsI7D48D942zmTap1v3mppEG7eBh71+LE4G1iZFnGt5VFzp3GaDLFERBg5qGUbVx/lCB8URa4f1fkjWjeIlXcnOUZIRgf0af2FywgOb/tEBD/X5bH2yCeAdHnfgtuFL3FSrjXJSQ5HGelRSUNHqRTocypWxW0mpIB5699tDlsbJyc62FvayIhEjkkVepJDqare87V1bcm3PZ6UQaoVxmJMGoSmDhSJDWZv3fTBp0H2TM4vZ0apM6f1yctgTUSbe4iB/V3OEj4+zXDgthrw+H4pXK3lulSTY/JvUyEqAnLmASSsvravQTCha53YwqqJYaRKlqfD95hZUscvri6EPFhhCxoVdt5Dea+I5/4IraVOZ7nAk38R7raQ0qtq7xwP5c0E48AurwdqnFWgESfD6DUbzptfQLiv22pqu3e7NGKunV0xnHlYc/S+a/QeEDaevhvstc7ZF7BY/g9uMXO82sMC4RfkQ=
  - secure: N/uKosIvDG/SUngM5XC39bb0aV1PpCFhQ9Zv7dN3PDNemlSExdTuopIPX+7eSgazOln5i3tlYREkHsbNUM3BXWMZHJRP1GyeUTtqZUlNQBzsacWCTBPLHmgSVy2yhUptj3beM+AIcyqpHShfXsSxUyq0Iew3+7J9fLxk/qemfjoD7CJsUAD8NV5CCPzZH20+rEnFrYMBrO727MhqRbeQVBmI3MiWZVhe0Un7Ui5VFwAm+9anJJ8ZELh3lOB4/ruLPNE07L2dL82vTVF51gqc6VXNZi6RYXQPB9yxBQg7ELCle2ETWpqwARDCJmr0JR9ZkE2QhKZMA1C0PgFV3hkrV+56aLAdAQ83E6T8+TBLtuueJCa1v8L1rVDQc9+KILHpO1L4gmXiCBE3H4Q5blTa5SGLmSbRjGwW0n/sOEaklwhOPL/epQpeI+yuEUWu2NZv56cJOA98LJcW/wAYNUz/P8uMoINEh8Zp31ejViG11PSK9VZ7G5Z/u6MOdCZJiq+ULBK/b2Gag6AgQmhpZ/y7F8BKIl654rogVcHTVkOBsvmKt2/rA3wC3s9z5gks28t9gPWbGYhPOr6eelZnysbExCgqbx6j+/ziJHSz7qn7CiCi2JGbVSy6tgX4iRwN90SzF2fXH36VfPKx6oGjA0zDekh8m0BoLaDKiaXDVnBcoyg=
